In [1]:
import numpy as np

In [2]:
a= np.random.randint(0, 100, size=(2, 3, 5))
a_1 = np.random.rand(2,4,5)

In [3]:
print(a)

[[[32  5 64 17 59]
  [98 68  8 81 31]
  [38 17  5 44 62]]

 [[66 20 94 74 11]
  [75 25 99 80 39]
  [73 48 19 24 45]]]


In [4]:
b=np.ones((5, 2,3))

In [5]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [6]:
b.shape

(5, 2, 3)

In [7]:
a.shape=b.shape

In [8]:
#no because they have diferent shape.

In [9]:
c=b.reshape(5,2,3)

In [10]:
c.shape

(5, 2, 3)

In [11]:
d=a+b

In [12]:
e=a*c

In [13]:
e

array([[[32.,  5., 64.],
        [17., 59., 98.]],

       [[68.,  8., 81.],
        [31., 38., 17.]],

       [[ 5., 44., 62.],
        [66., 20., 94.]],

       [[74., 11., 75.],
        [25., 99., 80.]],

       [[39., 73., 48.],
        [19., 24., 45.]]])

In [14]:
a

array([[[32,  5, 64],
        [17, 59, 98]],

       [[68,  8, 81],
        [31, 38, 17]],

       [[ 5, 44, 62],
        [66, 20, 94]],

       [[74, 11, 75],
        [25, 99, 80]],

       [[39, 73, 48],
        [19, 24, 45]]])

In [15]:
d_max=np.max(d)

In [16]:
d_max

100.0

In [17]:
d_min=np.min(d)

In [18]:
d_min

6.0

In [19]:
d_mean=np.mean(d)

In [20]:
d_mean

48.36666666666667

In [24]:
f=np.empty([2,3,5])

In [26]:
print(f)

[[[32.  5. 64. 17. 59.]
  [98. 68.  8. 81. 31.]
  [38. 17.  5. 44. 62.]]

 [[66. 20. 94. 74. 11.]
  [75. 25. 99. 80. 39.]
  [73. 48. 19. 24. 45.]]]


In [27]:
d=a+c

In [28]:
d_max=np.max(d)
d_min=np.min(d)
d_mean=np.mean(d)

In [64]:
f = [[[25 if d_min<i<d_mean else 75 if d_mean<i< d_max else 0 if i == d_min else 100 for i in z] for z in h] for h in d]

In [66]:
f

[[[25, 0, 75], [25, 75, 75]],
 [[75, 25, 75], [25, 25, 25]],
 [[0, 25, 75], [75, 25, 75]],
 [[75, 25, 75], [25, 100, 75]],
 [[25, 75, 75], [25, 25, 25]]]

In [70]:
for h in d:
    for z in h:
        for i in z:
            if d_min<i<d_mean:
                i=25
            elif d_mean<i< d_max:
                i=75
            elif i == d_min:
                i=0
            else:
                i=100

In [74]:
j = [[["a" if d_min<i<d_mean else "b" if d_mean<i< d_max else "c" if i == d_min else "d" for i in z] for z in h] for h in d]

In [75]:
j

[[['a', 'c', 'b'], ['a', 'b', 'b']],
 [['b', 'a', 'b'], ['a', 'a', 'a']],
 [['c', 'a', 'b'], ['b', 'a', 'b']],
 [['b', 'a', 'b'], ['a', 'd', 'b']],
 [['a', 'b', 'b'], ['a', 'a', 'a']]]